_base_: ./pretrain_gpt_base.yaml

Global:
  global_batch_size: 
  local_batch_size: 2
  micro_batch_size: 2


Model:
  vocab_size: 50304
  hidden_size: 2048
  num_layers: 24
  num_attention_heads: 16
  ffn_hidden_size: 
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: True


Distributed:
  dp_degree: 2
  mp_degree: 2
  pp_degree: 2
  sharding:
    sharding_degree: 1
    sharding_stage: 1
